#server:
#  port: 8081
#  servlet:
#    context-path: /test # to np. "/actuator" zmienia na "/test/actuator", dorzuca "/test" do urli
#springdoc:
#  show-actuator: true
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'